name = "grpc"
types = ["grpc"]
version = "v0.1.0"
language = "go"
product = "EXAMPLE"

[tests]
  execute_lifecycle = false

# Custom service settings to be loaded inside its Definitions struct.
[service]
  foo = "hello world"
  bar = 42
